title: Katherine Picazo
author: Katherine Picazo
email: katherine.picazo@edu.sait.ca
description: > # this means to ignore newlines until "show_excerpts:"
  This site is mostly a collection of old reviews about
  some of the manga I've read over the years.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: siovale
    github:  katrose
    linkedin: katherinepicazo

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

 # Paginate settings
paginate: 5

# Collections
collections:
  projects:
    output: true